apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuel-cost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuel-cost
  template:
    metadata:
      labels:
        app: fuel-cost
    spec:
      containers:
        - name: server
          image: gcr.io/fuel-cost-2019/fuel-cost:kubernetes-stuff
          livenessProbe:
            httpGet:
              path: /isAlive
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"