apiVersion: v1
kind: Service
metadata:
  name: fuel-cost-external
spec:
  type: LoadBalancer
  loadBalancerIP: "35.204.53.27"
  selector:
    app: fuel-cost
  ports:
    - name: http
      port: 80
      targetPort: 8080